apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: samples.skadia.gopro.com
spec:
  group: skadia.gopro.com
  names:
    kind: Sample
    listKind: SampleList
    plural: samples
    singular: sample
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
